image: beet/box

steps:
  - name: Test
    plugin: Script
    script:
      - pwd

#  - name: Install Docker
#    plugin: Script
#    script:
#      - sudo apt-get update
#      - sudo apt-get install apt-transport-https ca-certificates
#      - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
#      - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
#      - sudo apt-get update
#      - sudo apt-get purge lxc-docker
#      - apt-cache policy docker-engine
#      - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install linux-image-extra-$(uname -r) linux-image-extra-virtual
#      - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install docker-engine
#      - sudo service docker start
#
#  - name: Build
#    plugin: Script
#    script:
#      - docker pull beet/box

#  - name: Build
#    plugin: Script
#    script:
#      - composer self-update
#      - composer install
#
#  - name: Drupal code review
#    plugin: Script
#    script:
#      - composer global require alexdesignworks/dcr:*
#      - dcr init
#      - bash dcr -vv --no-messages
#
#  - name: Install
#    plugin: Drupal
#    drupalVersion: 8
#    subDirectory: docroot
#    runInstall: standard
