---

# Beetbox settings.

beet_domain: sandbox.local
beet_provision_playbook: build
beet_root: "{{ beet_base }}/docroot"



# Drupal settings.

drupal_install_site: yes
drupal_install_profile: sandbox



# Drupal code review settings.

dcr_standards: "../../drupal/coder/coder_sniffer,../../alexdesignworks/dcr/php_codesniffer,../../../.dcr"



# Custom settings.

sandbox_env_path: "{{ beet_base }}/vendor/bin"
sandbox_files:
  - src: config
  - src: sandbox.info.yml
  - src: sandbox.profile
  - src: ../modules
    dest: modules/custom
  - src: ../themes
    dest: themes/custom
